#!/usr/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later

cp -f "$(type -P lone)" lone.patched || exit 1
lone-embed lone.patched "$(dirname "${0}")/../segment" || exit 2

at-phdr-invariant lone.patched
