#!/usr/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later

cp -f "${LONE_BUILD}/lone" lone.patched || exit 1
lone-embed lone.patched "${LONE_TEST_CASE}/segment" || exit 2

at-phdr-invariant lone.patched
