#!/usr/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later

cp -f "$(type -P lone)" lone.patched || exit 1
lone-embed lone.patched "$(dirname "${0}")/../segment" || exit 2

./lone.patched < /dev/null
code="${?}"
if [[ "${code}" != 42 ]]; then
  >&2 printf 'embedded segment exited %s, expected 42\n' "${code}"
  exit 3
fi
