#!/usr/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later

cp -f "${LONE_BUILD}/lone" lone.patched || exit 1
lone-embed lone.patched "${LONE_TEST_CASE}/segment" || exit 2

./lone.patched < /dev/null
code="${?}"
if [[ "${code}" != 42 ]]; then
  >&2 printf 'embedded segment exited %s, expected 42\n' "${code}"
  exit 3
fi
