name: lone

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: archlinux:base-devel

    strategy:
      fail-fast: false

      matrix:
        compiler:
          - name: cc
            env:
              CC: cc
          - name: gcc
            env:
              CC: gcc
          - name: clang
            env:
              CC: clang
        linker:
          - name: ld
            env:
              LD: ld
          - name: lld
            env:
              LD: lld
          - name: mold
            env:
              LD: mold
          - name: mold+spare-segments
            env:
              LD: mold
              LDFLAGS: -Wl,--spare-program-headers,2

    env:
      CC: ${{ matrix.compiler.env.CC }}
      LD: ${{ matrix.linker.env.LD }}
      CFLAGS: ${{ matrix.compiler.env.CFLAGS }}
      LDFLAGS: ${{ matrix.linker.env.LDFLAGS }}

    name: ${{ matrix.compiler.name }} ${{ matrix.linker.name }}

    steps:
    - name: Set up pacman keys
      run: pacman-key --init

    - name: Update packages and install dependencies
      run: pacman -Syu --noconfirm clang lld llvm mold

    - name: Checkout lone repository
      uses: actions/checkout@v4

    - name: Build lone
      run: make --jobs --output-sync lone

    - name: Build lone's tools
      run: make --jobs --output-sync tools

    - name: Build lone's test suite
      run: make --jobs --output-sync tests

    - name: Test lone
      run: make test

  analyze:
    name: CodeQL analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]

    steps:
    - name: Checkout lone repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    - name: Build lone
      run: make

    - name: Perform CodeQL analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"
